<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" Version="6.44.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Amiasea.Enterprise.Common\dotnet\Amiasea.Enterprise.Common\Amiasea.Enterprise.Common.csproj" />
  </ItemGroup>

</Project>
